development:
  adapter: postgresql
  database: sightings_development

test:
  adapter: postgresql
  database: sightings_test

development:
  adapter: postgresql
  database: world_sightings_development

test:
  adapter: postgresql
  database: world_sightings_test
